name: iOS (simulator) build
on:
  workflow_dispatch:  # keep only this trigger to avoid branch confusion
jobs:
  build-ios-sim:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Ensure minimal Capacitor files exist
        run: |
          test -f capacitor.config.json || cat > capacitor.config.json <<'EOF'
          {
            "appId": "com.mathe.glowup",
            "appName": "GlowUp Money",
            "webDir": "web",
            "bundledWebRuntime": false
          }
          EOF
          mkdir -p web
          test -f web/index.html || cat > web/index.html <<'EOF'
          <!doctype html><meta charset="utf-8"><title>GlowUp – CI Smoke Test</title>
          <body style="display:grid;place-items:center;height:100vh;font-family:system-ui"><h1>✅ Hello iOS</h1></body>
          EOF

      - name: Install Capacitor toolchain
        run: |
          npm i -D @capacitor/cli @capacitor/core @capacitor/ios

      - name: Prepare iOS platform
        run: |
          npx cap add ios || true
          npx cap sync ios
          ls -la ios || true
          ls -la ios/App || true

      - name: Install CocoaPods and pods
        run: |
          sudo gem install cocoapods -NV || true
          cd ios/App
          pod repo update || true
          pod install --repo-update
          cd ../..

      - name: Build (Simulator) – iPhone 15 Pro (latest iOS)
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
        run: |
          set -euo pipefail
          if [ -f "ios/App/App.xcworkspace" ]; then
            xcodebuild \
              -workspace ios/App/App.xcworkspace \
              -scheme App \
              -configuration Debug \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
              -derivedDataPath build \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean build
          else
            xcodebuild \
              -project ios/App/App.xcodeproj \
              -scheme App \
              -configuration Debug \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
              -derivedDataPath build \
              CODE_SIGNING_ALLOWED=NO CODE_SIGN_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean build
          fi

      - name: Upload simulator artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: build/Build/Products/**/App.app
