name: iOS (simulator) build

on:
  workflow_dispatch:

jobs:
  build-ios-sim:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Ensure minimal Capacitor app
        run: |
          set -e
          test -f capacitor.config.json || cat > capacitor.config.json <<'EOF'
          { "appId": "com.mathe.glowup", "appName": "GlowUp Money", "webDir": "web", "bundledWebRuntime": false }
          EOF
          mkdir -p web
          test -f web/index.html || echo '<!doctype html><title>Hello iOS</title><body style="font-family:system-ui">✅ Hello iOS</body>' > web/index.html

      - name: Install Capacitor toolchain
        run: npm i -D @capacitor/cli @capacitor/core @capacitor/ios

      - name: Prepare iOS platform
        run: |
          npx cap add ios || true
          npx cap sync ios
          ls -la ios || true
          ls -la ios/App || true

      - name: Install CocoaPods and pods
        run: |
          if ! command -v pod >/dev/null 2>&1; then sudo gem install cocoapods -NV; fi
          cd ios/App
          pod install --repo-update
          cd ../..

      - name: Build (Simulator)
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
        run: |
          set -e
          if [ -f "ios/App/App.xcworkspace" ]; then
            xcodebuild -workspace ios/App/App.xcworkspace \
              -scheme App -configuration Debug -sdk iphonesimulator \
              -destination 'generic/platform=iOS Simulator' \
              -derivedDataPath build \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean build
          else
            xcodebuild -project ios/App/App.xcodeproj \
              -scheme App -configuration Debug -sdk iphonesimulator \
              -destination 'generic/platform=iOS Simulator' \
              -derivedDataPath build \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              clean build
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: build/Build/Products/**/App.app
